### ISSUE TITLE
MEP v1.7.0

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#1057]
# TODO

### Avant la MEP

- [x] Essayer la copie des données REG en intégration avant la MEP

### Backup

- [x] Pull du repo
- [x] Renommer MONITORFISH_LOGS_GID en MONITORFISH_LOGS_AND_BACKUPS_GID dans ~/.monitorfish
- [x] Créer le dossier de backup et lui attribuer le groupe MONITORFISH_LOGS_AND_BACKUPS_GID
```
cd /opt
sudo mkdir monitorfish_backups
sudo chown :dp_backmf monitorfish_backups # (mettre le groupe qui possède le dossier)
sudo chmod 775 monitorfish_backups/
```
- [x] Ajouter MONITORFISH_BACKUPS_FOLDER dans ~/.monitorfish
- [x] Mettre à jour le crontab (cf infra/remote/backup/crontab.txt)
- [ ] Tester la restauration

### Prefect

- [x] [Upgrader docker](https://docs.docker.com/engine/install/debian/#install-using-the-repository) en >= 20.10
- [x] MAJ Prefect et agent sur la machine :
  - [x] Installer pyenv :
    - [x] Pré-requis : https://github.com/pyenv/pyenv/wiki#suggested-build-environment
    - [x] Installation : 
  ```
  curl https://pyenv.run | bash
  exec $SHELL
  ```
  - [x] Installer python 3.8.7 : `pyenv install 3.8.7`
  - [x] Créer un environnement virtuel : `python -m venv ~/venv`
  - [x] Activer l'environnement virtuel : `source ~/venv/bin/activate`
  - [x] Installer prefect 0.15.11 : `pip install prefect==0.15.11`

### Table reglementation_peche

- [x] Au CROSS (table `reglementation_peche`) :
```
DROP VIEW reglementation_peche_view;

ALTER TABLE public.reglementation_peche
    DROP COLUMN date_fermeture,
    DROP COLUMN date_ouverture,
    DROP COLUMN periodes,
    DROP COLUMN engins,
    DROP COLUMN engins_interdits,
    DROP COLUMN especes,
    DROP COLUMN quantites,
    DROP COLUMN taille,
    DROP COLUMN especes_interdites,
    DROP COLUMN autre_reglementation_especes,
    DROP COLUMN documents_obligatoires,
    DROP COLUMN autre_reglementation,
    DROP COLUMN references_reglementaires_a_venir;

ALTER TABLE public.reglementation_peche
    RENAME COLUMN layer_name to topic;
ALTER TABLE public.reglementation_peche
    RENAME COLUMN zones to zone;
ALTER TABLE public.reglementation_peche
    RENAME COLUMN references_reglementaires to regulatory_references;
ALTER TABLE public.reglementation_peche
    RENAME COLUMN mesures_techniques to regulatory_details;
ALTER TABLE public.reglementation_peche
    RENAME TO regulations;

UPDATE prod.regulations
    SET topic = REPLACE(topic, '_', ' ');

UPDATE prod.regulations
    SET zone = REPLACE(zone, '_', ' ');

CREATE OR REPLACE VIEW regulations_view AS SELECT id, law_type, facade, topic, zone, region, fishing_period,
                                                           species, gears, regulatory_references, geometry_simplified,
                                                           row_hash, next_id
                                                    FROM regulations;
ALTER TABLE regulations_view RENAME COLUMN geometry_simplified to geometry;

```

Et le trigger:
```

DROP FUNCTION IF EXISTS prod.compute_reglementation_md5 CASCADE;

CREATE FUNCTION prod.compute_reglementation_md5() RETURNS trigger AS $$
    BEGIN
        NEW.row_hash := md5( 
			COALESCE(NEW.law_type::text, '') ||
			COALESCE(NEW.facade::text, '') ||
			COALESCE(NEW.topic::text, '') ||
			COALESCE(NEW.zone::text, '') ||
			COALESCE(NEW.region::text, '') ||
			COALESCE(NEW.fishing_period::text, '') ||
			COALESCE(NEW.species::text, '') ||
			COALESCE(NEW.gears::text, '') ||
			COALESCE(NEW.regulatory_details::text, '') ||
			COALESCE(NEW.regulatory_references::text, '') ||
			COALESCE(NEW.geometry::text, '')  ||
			COALESCE(NEW.next_id::text, '') 
		);
        RETURN NEW;
    END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER compute_reglementation_md5
    BEFORE INSERT OR UPDATE ON prod.reglementation_peche
    FOR EACH ROW
    EXECUTE PROCEDURE prod.compute_reglementation_md5();
```

- [x] A DAM-SI

Suite au changement de la table `reglementation_peche` en `regulations`

```
curl -v -u admin:geoserver -X POST http://0.0.0.0:8001/geoserver/rest/workspaces/monitorfish/datastores/monitorfish_postgis/featuretypes -H  "accept: text/html" -H  "content-type: application/json" -d @- << EOF
{
  "featureType": {
    "name": "regulations",
    "nativeName": "regulations_view",
    "title": "Regulatory Areas",
    "nativeCRS": "EPSG:4326",
    "srs": "EPSG:4326",
    "enabled": true,
  }
}
EOF

curl -v -u admin:geoserver -X POST http://0.0.0.0:8001/geoserver/rest/workspaces/monitorfish/datastores/monitorfish_postgis/featuretypes -H  "accept: text/html" -H  "content-type: application/json" -d @- << EOF
{
  "featureType": {
    "name": "regulations_write",
    "nativeName": "regulations",
    "title": "Regulatory Areas for write operation",
    "nativeCRS": "EPSG:4326",
    "srs": "EPSG:4326",
    "enabled": true,
  }
}
EOF
```
### Pipeline

- [x] Enregistrer les flows : `make register-pipeline-flows-prod`
- [x] Copier `infra/configurations/prefect_agent/backend.toml` dans `~/.prefect/backend.toml`
- [x] Lancer l'agent : `make run-pipeline-agent-prod`
- [x] Faire tourner le flow de `vessels` avant que `update_beacon_malfunctions` ne tourne
- [x] Faire tourner le flow `Fishing gears`
- [x] Faire tourner le flow `Control objectives`
- [x] Faire tourner le flow `Ports`
