### ISSUE TITLE
TODO Prochaine MEP

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#1844]
### A faire pendant la MEP
- [ ] [Config du logger du dockerd](https://docs.docker.com/config/containers/logging/configure/#configure-the-default-logging-driver) en  `local` sur `prefekt` `monitorenv` et `monitorfish` - s'assurer que les containers sont supprimés puis recréés (nécessite un redémarrage forcé pour les services en ajoutant `--build <service-name>` à la commande make) 

### Pipelines

- [ ] Executer tous les flows et s'assurer qu'ils soient verts

### Affichage dernière position navires

- [ ] Affichage des segments de flotte et autres infos d'étiquette
- [ ] Affichage du tableau des dernières positions
- [ ] Filtre sur le tableau des dernières positions
- [ ] Télécharger le tableau (situ VMS)
- [ ] Création et affichage d'un filtre sur les navires
- [ ] Suppression d'un filtre

### Réglementation

- [ ] Recherche dans la réglementation
- [ ] Affichage d'une couche réglementaire
- [ ] Affichage des metadonnées d'une couche réglementaire

### Zones admin

- [ ] Afficher les différentes zones admin
 
### Fonds de cartes

- [ ] Afficher les différents fonds de cartes
 
### Affichage fiche navire

- [ ] Onglet JPE
- [ ] Onglet infos navire
- [ ] Onglet contrôles

### Piste navire

- [ ] Affichage de la piste depuis le dernier DEP
- [ ] Affichage de la piste sur 24h
- [ ] Détail des positions (tableau)
- [ ] Coloration de piste
- [ ] Estimation de la position actuelle

### Alertes
- [ ] les alertes de chalutage s'affichent dans l'écran d'alertes
- [ ] les navires en alertes apparaissent en rouge sur la carte
- [ ] Zoom sur un navire en cliquant sur une alerte

### Avaries
- [ ] les avaries s'affichent dans l'écran d'avaries
- [ ] Zoom sur un navire en cliquant sur une avarie
- [ ] Les notifications sont envoyées (mockées en intégration) et apparaissent dans le fil de l'avarie
