### ISSUE TITLE
Affichage de la liste des réglementations dans l'interface REG

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#285]
**Description**

En tant qu'administratrice des couches réglementaires
Je veux afficher toutes les couches réglementaires
Afin de visualer les métadonnées de ces dernières

**Critères**

    Étant donné que le Geoserver contient des couches réglementaires
    Quand j'arrive sur l'URL `/backoffice`
    Alors j'affiche la liste des couches et une carte de la France sans couche d'affiché par défaut

**Ecran**

Lien XD : https://xd.adobe.com/view/ea58d3a9-33cd-4a15-a3e3-2e07d3048eb8-bf0b/

**Comment by AdelineCelier** [comment]
@AudreyBramy Hello ! Juste pour info j'ai màj le fichier Adobe XD avec les écrans suivants (ceux pour le formulaire de création d'une nouvelle réglementation). Je sais que ce n'est pas pour tout de suite, mais ayant refait une passe dessus, j'ai préféré les caler dans le fichier. 

Et concernant les écrans sur lesquels tu travailles en ce moment, je me suis rendu compte que j'avais laissé le bouton "modifier la réglementation" dans le bandeau en bas, or il n'a plus lieu d'être, donc je l'ai retiré. J'espère que ça ne chamboulera pas trop ce que tu as déjà fait ! 

N'hésite pas si tu as des questions.

**Comment by AdelineCelier** [comment]
**Ajustements UX/UI**
- typo des titres ("RÉGLEMENTATION FRANCE", "REG LOCALE", etc.) : les mettre en gras. J'ai l'impression que la typo n'est pas tout à fait la même que sur les maquettes (cf. capture, à gauche le backoffice, à droite la maquette), c'est bien de la Marianne en 16 px ? 
![image](https://user-images.githubusercontent.com/71878648/124137242-c6751700-da85-11eb-9b68-1fc8ac143236.png)

- agrandir la marge entre les deux colonnes (REG FRANCE / REG UE) : 35 px
- réduire la hauteur de l'encart contenant le bouton "Saisir une nouvelle réglementation" : 60 px 
- passer en gris (#969696) les mentions "x zone(s)" en face du nom des thématiques
-  aligner les icônes "œil" des thématiques et des zones (cf. capture ci-dessous) 
- réduire l'espacement entre le carré de couleur et le nom de la zone : 10 px (cf. capture ci-dessous)
-

**Comment by AudreyBramy** [comment]
J'ai bien vu ces retours @AdelineCelier, je m'en occupe.

**Comment by AdelineCelier** [comment]
Super merci @AudreyBramy :)
D'ailleurs, je me rends compte que je ne suis pas sure de t'avoir repartagé la dernière version des écrans XD, avec notamment le bouton qui servira à modifier la reg d'une zone, qui apparaît au survol de son nom. 
Les voici : https://xd.adobe.com/view/b1ea0a09-9296-419d-84cb-f72afc2931eb-e4b9/

**Comment by AudreyBramy** [comment]
- [ ] il n'y a pas de scroll qui apparaît quand je déploie des tiroirs (Windows 10 - Firefox 78)
- [ ] quand on ouvre un tiroir de reg ("REG LOCALE", ou "R(UE) 2019/1241" par ex), ce serait bien que ça referme les autres tiroirs de même niveau déjà ouverts
- [ ] fixer en bas d'écran le bandeau avec le bouton "saisir une nouvelle réglementation"

**Comment by AudreyBramy** [comment]
- [ ] typo des titres ("RÉGLEMENTATION FRANCE", "REG LOCALE", etc.) : les mettre en gras. J'ai l'impression que la typo n'est pas tout à fait la même que sur les maquettes (cf. capture, à gauche le backoffice, à droite la maquette), c'est bien de la Marianne en 16 px ?
- [ ] agrandir la marge entre les deux colonnes (REG FRANCE / REG UE) : 35 px
- [ ]  réduire la hauteur de l'encart contenant le bouton "Saisir une nouvelle réglementation" : 60 px
- [ ]  passer en gris (#969696) les mentions "x zone(s)" en face du nom des thématiques
- [ ] aligner les icônes "œil" des thématiques et des zones (cf. capture ci-dessous)
- [ ] réduire l'espacement entre le carré de couleur et le nom de la zone : 10 px (cf. capture ci-dessous)
- [ ] rajouter le placeholder dans la barre de recherche : "Rechercher une zone par son nom, sa référence réglementaire ou son numéro de tracé " en gris (#969696)
- [ ] rajouter le placeholder dans la barre de recherche : "Rechercher une zone par son nom, sa référence réglementaire ou son numéro de tracé " en gris (#969696)

**Comment by AudreyBramy** [comment]
- [ ] le bouton qui servira à modifier la reg d'une zone, qui apparaît au survol de son nom.

**Comment by AudreyBramy** [comment]
Je pense que dans la PR[#448](https://github.com/MTES-MCT/monitorfish/pull/448) j'ai fait le tour de tes retours @AdelineCelier.
Concernant ce point ' le bouton qui servira à modifier la reg d'une zone, qui apparaît au survol de son nom.' je vais l'ajouter dans ma tâche sur la saisir d'une nouvelle réglementation.
Dis moi ce que tu en penses et surtout si le soucis est résolu sur Firefox.
J'ai testé avec la même version mais sur MacOs donc à voir si c'est ok de ton côté.

**Comment by AdelineCelier** [comment]
@AudreyBramy, bien reçu. C'est noté pour l'intégration du bouton de modification d'une zone reg. 

J'ai tout checké, il reste juste deux-trois points : 
- les icônes "œil" ne sont toujours pas tout à fait alignées chez moi, entre la ligne de la thématique et la ligne de la zone : 
![image](https://user-images.githubusercontent.com/71878648/125447162-16861bb8-3d6b-4778-8e3a-5908ce5253f6.png)

- de mon côté j'ai toujours un problème de typo pour les titres : ils ne s'affichent pas en gras (cf. capture). Loup pense que ça vient de Windows, parce que sur son Linux ça s'affiche bien...est-ce que tu aurais une idée d'où ça peut venir ? Si c'est trop complexe on laisse tomber mais j'avoue que ça me chiffonne 
![image](https://user-images.githubusercontent.com/71878648/125447010-aaedf20d-aece-4534-8e04-dd457002db05.png)

- le scroll fonctionne bien maintenant c'est good. Je me demande juste si l'on ne peut pas gagner un peu en visibilité des zones, en agrandissant un peu le scroll...et du coup s'il n'y a pas de scroll global mon bandeau avec le bouton "saisir une nouvelle réglementation" n'a plus vraiment lieu d'être. Il me semble qu'on avait discuté au tout début de cette histoire de scroll, le mieux serait qu'on s'appelle pour qu'on en discute rapidement ? 

- est-ce que tu peux juste rajouter un séparateur fin en-dessous de la dernière zone d'une liste, afin qu'elle soit visuellement séparée du titre de la section suivante ? cf ci-dessous : 
![image](https://user-images.githubusercontent.com/71878648/125447416-c982e459-5f7b-4b91-b4ed-684bbe0eb96e.png)
![image](https://user-images.githubusercontent.com/71878648/125447517-381df3b9-4e60-4150-aabd-c5fe64e83147.png)

**Comment by AdelineCelier** [comment]
@AudreyBramy j'ai mis à jour le lien XD pour la modification du bouton "saisir une nouvelle réglementation" : on supprime le bouton du bas en on le transforme en "+" à côté de la barre de recherche. Il faut peut-être juste rajouter une infobulle "saisir une nouvelle réglementation" au survol du bouton ?

**Comment by AdelineCelier** [comment]
- alignement des icônes "œil" 👍🏻 
- agrandissement du scroll 👍🏻 
- intégration de la loupe dans la barre de recherche + ajout du bouton "saisir une nouvelle reg" 👍🏻 
- ajout d'un séparateur à la fin de la liste des zones d'une thématique 👍🏻 

Points restants : 
- comme discuté sur Slack, la bordure de la barre de recherche et la loupe doivent être en #D6D6D6, il me semble qu'elles sont en #EDEDED en ce moment
- idem pour tous les séparateurs, épais et fins, il sont tous en #D6D6D6 (mea culpa je me rends compte que ce n'était pas tout à fait le cas sur le XD, j'ai mis à jour)

**Comment by AudreyBramy** [comment]
@AdelineCelier je suis en train d'apport les modifications sur les couleurs.
En revanche, je n'arrive pas à reproduire chez moi ton problème avec les typos. J'attendais justement que tu puisses tester chez toi. Je vais creuser.

**Comment by AudreyBramy** [comment]
C'est bien sur tous les textes qui sont censé être en gras ? 
Peux-tu me rappeler la version de ton firefox ? 
Est-ce que tu as testé avec un autre navigateur ?

**Comment by AdelineCelier** [comment]
Alors oui j'ai l'impression que c'est pour les textes en gras & medium. C'est surtout visible sur les titres en majuscule, qui sont en Marianne bold, 16 px (sur la maquette, ce sont les titres gris "REG. FRANCE" et "REG. UE" + les titres gris foncé "R(UE)1241", REG. LOCALE / MEMN" etc.). Mais c'est aussi visible sur les noms des thématiques et des zones, qui sont en medium, et s'affichent moins grasses dans Firefox. 

Après vérification, j'ai l'impression que ça marche dans Chrome (version 91.0.4472.124) ! Du coup je vois que les titres gris foncé ("R(UE)1241", REG. LOCALE / MEMN" etc.) ne sont pas en gras aujourd'hui. Mais le reste s'affiche bien en gras ou en medium.
La version de Firefox sur laquelle ça déconne : 78.2.0esr

**Comment by AudreyBramy** [comment]
Ok d'acc. 
Je corrige donc pour ces titres. On va y arriver ^^.
Du coup, j'ai vérifier, firefox est déjà à la version 91 sur Windows 10.
Est-ce que tu penses que tu pourrais upgrader ta version ?

**Comment by AdelineCelier** [comment]
Haha désolée c'est un peu laborieux cette histoire de typos...bon et du coup j'ai vérifié avec l'équipe technique, ils ne peuvent installer que la version 78.11 de Firefox, parce que c'est la dernière à avoir été validée par le service sécurité ou chais pas quoi...le retard dans les administrations... du coup si c'est trop compliqué d'ajuster le bug pour la version 78 tant pis, on met de côté pour l'instant. De toutes façons ils sont pas mal à aller sur Chrome aussi
