### ISSUE TITLE
EPIC - Nouveaux statuts de missions

### ISSUE THREAD

**Issue by louptheron** [MTES-MCT/monitorfish#3036]
## Maquette
https://xd.adobe.com/view/06d04fac-8722-43f0-b5d5-90601b20697e-5383/grid

### Liste 

- [x] Ajout d'un filtre sur statut & complétion des données #3037
- [x] Ajouter deux colonnes status et complétion des données #3037
  - [x] Si un état est non-complété parmis la mission et les actions, on passe à "à compléter" 
- [x] Rajouter les filtre "Missions avec actions pêche" #3037
- [x] Supprimer le filtre "Ouvert par" #3037

#### Mission
- [x] Afficher les tags de complétions #3037
- [x] Afficher le nouveau bandeau "Toast" lors de la création d'une mission #3038
- [x] à chaque enregistrement, calculer l'état de complétion de la mission et de l'action pour l'enregistrer en BDD #3037
- [x] Afficher le bandeau quand on revient sur une mission terminée mais non-complétée #3038
- [x] Suppression de la clôture #3095 

#### Action
- [x] Revoir les headers des colonnes du formulaire #3038
- [x] à chaque enregistrement, calculer l'état de complétion de la mission et de l'action pour l'enregistrer en BDD #3037
- [x] En dessous du titre de l'action, afficher les champs à compléter, ex. "12 champs à compléter pour la stat" #3037

#### Liste des actions
- [x] Dans la liste des actions, rajouter un trait entre les actions #3038
- [x] Rajouter le point d'exclamation en-dessous de la date dans la liste d'action #3038
- [ ] Afficher "Des données ont été ajoutées par l'unité dans la mission." en récupérant les actions de rapportNav #3038

### Carte

- [x] Changer les tags de la popup mission et action #3039
- [x] Changer les couleurs des missions #3039

### Données

- [x] Rajouter le champ `completion` dans les actions #3037
- [x] Si le trigramme de clôture est présent dans les actions, on migre les `isClosed` en `COMPLETED` #3037

## Backend

- [ ] Calculer l'état de complétion dans le backend #3040

**Comment by louptheron** [comment]
Je clos, il reste juste le ticket "Des données ont été ajoutées par l'unité dans la mission."
