### ISSUE TITLE
Préavis – Optimisations complémentaires du chargement de la liste et de la fiche préavis

### ISSUE THREAD

**Issue by ivangabriele** [MTES-MCT/monitorfish#3237]
- [x] N'associer le comptage des signalements que dans la part des préavis paginés et non l'ensemble
- [ ] #3613
  - Quid des intervalles de date en temps réel ? Peut-être faut-il limiter le cache aux intervalles de dates fixes ?
  - Quid des préavis récents qui peuvent être mis à jour entre-temps et dont le Frontend a besoin de forcer le rechargement ?  
    Ex: ouvrir un préavis entre-temps modifié ou supprimé force le rechargement de la liste pour l'aligner avec les données de la fiche.
- [ ] Ne charger que la page supplémentaire lors d'un infinite scroll ?
  - Questions similaires aux 2 questions précédentes.
- [ ] #3464
- [x] Charger la fiche directement à partir des préavis manuel ou auto (et non en "essayant les deux") en envoyant un booléen à partir du Frontend pour expliciter s'il s'agit d'un préavis manuel ou auto.
- [x] Indexer `logbook_reports.report_id` pour optimiser le chargement des fiches auto. Si besoin (mais devrait être inutile une fois l'index ajouté) : préciser l'`operation_datetime` en plus du `report_id` dans les appels Frontend
- [x]  indexer l'operation_datetime en plus du report_id dans les appels Frontend pour charger la liste

**Comment by AdelineCelier** [comment]
Après la revue d'aujourd'hui, en inté en effet il y a encore des latences dans le chargement du détail d'un préavis.

**Comment by ivangabriele** [comment]
@louptheron je t'assigne celui-ci mais si les optimisations déjà faites suffisent à rendre le chargement des fiches et de la liste raisonnablement rapides, les autres ne me paraissent pas prios pour une v1.

**Comment by louptheron** [comment]
Il reste quelques points à creuser

**Comment by ivangabriele** [comment]
Clôturé car derniers points relativement inutile à l'exception de #3613 créé pour l'occasion.
