### ISSUE TITLE
EPIC – Amélioration continue JPE / Préavis

### ISSUE THREAD

**Issue by ivangabriele** [MTES-MCT/monitorfish#3279]
- [x] #3280
- [ ] Préavis – Séparer de manière propre les `ManualPriorNotification` des `AutoPriorNotification` (?) dans le domain du Backend.
- [ ] JPE – Voir s'il est possible d'avoir des classes directes pour couvrir les différents types de message dans le domain du Backend.
- [ ] JPE / Préavis – Voir s'il est possible de simplifier la logique d'enrichissement.
- [x] #3237
- [ ] JPE – Normaliser les noms `LogbookReport` et `LogbookMessage` en faisant un choix entre les deux (`LogbookReport` collerait à la base de données + à la prop `reportId`).
- [ ] JPE / Préavis – Passer tous les `flagState` en `CountryCode`
- ~~Préavis – Ajouter une base de données dédiée pour le stockage des bytearrays (ex: PDF)~~

**Comment by ivangabriele** [comment]
@louptheron 

- " JPE / Préavis – Voir s'il est possible de simplifier la logique d'enrichissement.`"Fait ?
- "Préavis – Séparer de manière propre les ManualPriorNotification des AutoPriorNotification (?) dans le domain du Backend." On peut le retirer à mon avis
