### ISSUE TITLE
EPIC - Préavis V2

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#3299]
## Fonctionnalités à faire en priorité après la V1

**Points nécessitant du design**
- [ ] Dans le formulaire des - 12 m, garder une trace des différentes diffusions faites auprès des unités. Challenger les utilisateurs sur le degré de précision avec lequel on doit stocker les infos. 
- [ ] Ajouter la fonctionnalité de téléchargement par lots, en cochant les cases au niveau du tableau

**Points prêts à être développés**
- [ ] #3320 
- [ ] #3340
- [ ] #3341
- [ ] #3335
- [ ] S'assurer que tous les scénarios de gestion des erreurs sont couverts. Je pense notamment à : 
  - cas où l'on sort du formulaire avant que la diffusion n'ait été faite => afficher le bandeau d'erreur au niveau de la vue liste
  - champs manquants dans le formulaire à la création ou l'édition => au clic sur "créer" ou "enregistrer",  ajouter un bandeau temporaire d'erreur disant "veuillez compléter les champs manquants" (utile notamment si champ manquant est sous la ligne de flottaison)
- [ ] Au clic sur le nom du navire (dans le formulaire d'édition comme dans le formulaire en lecture seule), ouvrir la fiche du navire sur la vue carto

## Fonctionnalités à creuser avec les utilisateurs après un temps d'usage

- [ ] Prévoir un mode brouillon ou un enregistrement auto dans le cas où le préavis manuel est long à saisir et que l'utilisateur est interrompu en cours de route. 
- [ ] Donner accès à la liste de diffusion à laquelle sera envoyée le préavis ? => à intégrer à la réflexion du ticket #3346

**Comment by AdelineCelier** [comment]
J'ai créé des tickets pour tous les points ci-dessus et les ai intégrés à la milestone "Préavis V2", pour expérimentation : https://github.com/MTES-MCT/monitorfish/milestone/1
Je ferme donc ce ticket.
