### ISSUE TITLE
Etat des lieux des fonctionnalités Neptune manquantes

### ISSUE THREAD

**Issue by VincentAntoine** [MTES-MCT/monitorfish#339]
Rapide sondage en salle de contrôle aujourd'hui, les 2 superviseurs et l'opérateur présents utilisent encore tous les 3 Neptune en complément de Monitorfish, pour :
- [x] Dans la recherche de positions entre deux date, prendre la date avec la journée incluse (https://github.com/MTES-MCT/monitorfish/issues/349)
- [x] Afficher la liste des positions dans un encart à partir de la fiche navire (https://github.com/MTES-MCT/monitorfish/issues/348)
- [x] Format ISO 8601 pour la colonne date (https://github.com/MTES-MCT/monitorfish/issues/347)
- [x] fonds de carte SHOM (https://github.com/MTES-MCT/monitorfish/issues/190)
- [x] date du dernier contrôle (https://github.com/MTES-MCT/monitorfish/issues/333)
- [x] points de situation VMS "on ne m'a pas dit que MonitorFish était validé"

**Comment by VincentAntoine** [comment]
Rapide sondage en salle de contrôle aujourd'hui, les 2 superviseurs et l'opérateur présents utilisent encore tous les 3 Neptune en complément de Monitorfish, pour :
- fonds de carte marins SHOM
- date du dernier contrôle
- points de situation VMS "on ne m'a pas dit que Monitorfish était validé"
