### ISSUE TITLE
Recherche reg 2 : évolutions

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitorfish#435]
### Reste à faire Adeline + Loup ###
- [ ] définir le mode de recherche dans les couches : se remémorer l'usage des champs de recherche thématiques
- [ ] ajouter un mode "visualisation de toutes les thématiques", comme dans le backoffice (pas prioritaire)
- [ ] ajouter une visualisation des tracés au survol des résultats de la recherche ? (mouf-mouf, à voir si faisable) => ticket #698 

### Design fait, reste à faire pour Loup ###

**Évolutions UX :** 
- [x] ajout des outils "rechercher des zones via la carte" (cf. ticket #128)
- [x] ajout de la catégorie "law_type" dans les résultats de la recherche
- [ ] ajout de l'indicateur nb de zones remontées/nb de zones total dans la thématique + possibilité d'afficher les zones "manquantes" dans la recherche
- [x] modification du mode de sélection des couches (checkbox) 
- [x] ajout du bouton "résumé reg" dès la recherche, pour afficher une reg ponctuellement sans avoir à ajouter la zone 
- [ ] ajout d'un bouton pour masquer/afficher le nom des couches carto sur la carte
- [ ] ajout de la légende des couleurs des zones reg

**Évolutions UI :** 
- [x] simplification du systèmes d'encarts/tiroirs
- [ ] Mise en relief du nom des law_type et thématiques (majuscules et gras)
- [x] Boutons loupe et + à revoir (aujourd'hui la loupe n'est pas un vrai bouton) (cf. ticket #391)

**Comment by AudreyBramy** [comment]
"Le nouveau design de la recherche REG est implémenté (Recherche reg 2 : évolutions #435), il en comprends pas les nouvelles fonctionnalités de recherche par selection directement sur la carto."

**Comment by AdelineCelier** [comment]
- [ ] Revoir les filets du tiroir "mes zones reg" : il manque le filet après la dernière zone d'une thématique + il y a un problème d'espace entre la dernière thématique de la liste et le volet "zones admin" (seulement quand une des thématiques est ouverte, faut un peu tester en cliquant partout pour voir si les filets s'agencent bien)
- [ ] il faudrait que les critères de recherche se ferment quand je fais une action dans le volet "mes zones reg" - notamment quand j'affiche le résumé réglementaire. Parce sinon le résumé s'affiche en décalé par rapport au volet : 
![image](https://user-images.githubusercontent.com/71878648/133054067-a1fac1b3-38fd-4709-a56e-c0588aebac45.png)

**Comment by AdelineCelier** [comment]
Ce ticket est trop tentaculaire 😱 
Je pense qu'il n'est plus d'actualité, étant donné que la meilleure manière d'améliorer la recherche reg aujourd'hui serait de reprendre les évolutions faites par Thomas dans ENV : 
- sur le mode de recherche par la carte
- sur le moteur de recherche
- sur les boutons et l'UI générale (qui de toutes façons a changé depuis ce ticket avec l'arrivée de la bibliothèque de composants)

Je ferme donc ce ticket de la mort 💀
